### ISSUE TITLE
Projectile Data Lab Main Checklist

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#1]
# Projectile Data Lab main checklist

## Design

- [x] **Sim folder and design doc created**
  - [x] Create sim folder
    in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs
    account
  - [x] Place design doc in the sim folder
- [x] **Review user feedback**
  - [ ] *If a
    Port:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=677625918)
  - [x] *If a new
    sim:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)
- [x] **Learning goals and standards identified** (Date: 5/5/23)
- [x] **Design concept complete**  (Date: 6/16/23)
- [x] **Wireframes complete** (Date: 6/22/23)
- [x] **Mockups complete** (Date: 8/4/23)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: 1/9/24)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 2/15/24)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Prototype items**
  - [ ] Auxiliary screenshots (at least 1 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate
  - [ ] Email/Twitter announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Send Simulation Notification from the Admin page (to alert translators)
- [x] **Pre-publication items**
  - [x] Auxiliary screenshots (up to 3 additional)
  - [x] Screen-specific screenshots for metadata service (
    see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] [Draft the Email announcement language](https://github.com/phetsims/tasks/issues/new?assignees=&labels=tasks%3Aemail&projects=&template=sim-announcement-email.md&title=Sim+Announcement+Email)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each
    screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429)
    for each screen (description, vocab words, questions for before/after sim use)
- [x] **Make sim visible on website**
  - [x] Clear "Metadata caches" on
    the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage)
    page
- [x] **Post-publication items**
  - [ ] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [x] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [ ] Deliver
    to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue
  - [x] Hold postmortem if applicable (Date: 5/15/24)
  - [x] Send Simulation Notification from the Admin page (to alert translators)

## Inclusive Features

- [x] Alternative Input (Started: 1/5/24) (Completed: 1/18/24)
- [x] Pan & Zoom
- [x] Sound & Sonification (UI)
- [x] Sound & Sonification (Pedagogical) - (include link to relevant sonification design document)
  - [x] Sound design complete (Started: 1/11/24) (Completed: 2/19/24)
  - [x] Development complete (Started: 1/11/24) (Completed: 4/9/24)
- [ ] Interactive Description - (link to description design & implementation checklist)
  - [ ] Description design complete (Started: ) (Completed: )
  - [ ] Development complete (Started: ) (Completed: )
  - [ ] Mobile description included
- [ ] Voicing - (include links to relevant voicing design document)

## Implementation

- [x] **Repository created** by
  following [new-repo-checklist.md](https://github.com/phetsims/phet-info/blob/main/checklists/new-repo-checklist.md) (
  Date: 11/17/23)
- [x] **Development started** (Date: 11/18/23)
- [x] **Sim is "feature complete"** (Date: 12/21/23)
- [x] **QA team "first look"** (Date: 1/10/24)
- [x] Interviews may happen around here (see above)
- [x] **Code review checklist completed"** (Date: 2/23/23)
- [x] **Sim team sign-off** (Date: 2/27/23)
- [x] **Code review completed** (Date: 3/6/23)
- [x] **Sim dev test completed** (Date: 4/1/23)
- [x] **Sim RC tests completed** (Date: 5/1/23)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks -
    see [conventions](https://github.com/phetsims/joist/blob/main/js/CreditsNode.js))
  - [x] Add CT tests for public query parameters that need testing. See examples
    in [listContinuousTests.js](https://github.com/phetsims/perennial/blob/main/js/listContinuousTests.js)
- [x] **Published** (Date: 5/3/24)

## QA

- [ ] *If a Port:* **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: 3/18/24)
- [x] **Dev testing completed** (Date: 4/1/24)
- [x] **First RC published** (Date: 4/9/24)
  - [x] Test matrices put
    in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 5/1/24)
