### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#32]

**Comment by pixelzoom** [comment]
Project board for PDL is https://github.com/orgs/phetsims/projects/85/views/1/.

**Comment by pixelzoom** [comment]
# PhET Code-Review Checklist (a.k.a "CRC")

* The responsible dev is responsible for removing the irrelevant parts
* A checked-off item doesn't mean "no problem here", it means "it was reviewed"
* Problems can be noted in side issues that reference this issue, or through `// REVIEW` comments in the code


## Specific Instructions

- [ ] Interactive Description is not supported for this simulation, and I removed that section from the code review checklist. Note package.json says `interactiveDescrption: true` in order to support keyboard navigation (which this simulation does support).
- [ ] Synchronous kickoff meeting
- [ ] Start with Projectile.ts, Field.ts, and PDLModel.ts (in that order)
- [ ] Please review recent changes to StopwatchNode.ts and how it is used in Projectile Data Lab. (See options `includePlayPauseResetButtons` and `otherControls`.)
- [ ] We would like to request assistance on https://github.com/phetsims/projectile-data-lab/issues/180
- [ ] We decided to err on the side of "passing in too many pieces" rather than "passing in too much in a single object", see for example: https://github.com/phetsims/projectile-data-lab/blob/630c94f46821ae8248821758b9b03042b61e5d9d/js/common-vsm/view/VSMScreenView.ts#L101-L115. We prefer it, but it makes for some longer call sites and constructor declarations. Does that seem good to you?
- [ ] PhET-iO API files are not yet checked in.
- [ ] Please be aware of open issues listed in https://github.com/orgs/phetsims/projects/85/views/1

## GitHub Issues

The following standard GitHub issues should exist. _If these issues are missing, or have not been completed, pause code
review until the issues have been created and addressed by the responsible dev._

- [ ] #184
- [ ] #185
- [ ] results of memory testing for `brands=phet`, see https://github.com/phetsims/projectile-data-lab/issues/24
- [ ] results of memory testing for `brands=phet-io` (if the sim is instrumented for PhET-iO), see https://github.com/phetsims/projectile-data-lab/issues/24
- [ ] #186
- [ ] #187
- [ ] credits (will not be completed until after RC testing), see https://github.com/phetsims/projectile-data-lab/issues/3

## **Build and Run Checks**

If any of these items fail, pause code review.

- [ ] #188
- [ ] Does the html file size seem reasonable, compared to other similar sims? UPDATE: 3MB for build/phet/en
- [ ] Does the sim start up? (unbuilt and built versions)
- [ ] Does the sim experience any assertion failures? (run with query parameter `ea`)
- [ ] Does the sim pass a scenery fuzz test? (run with query parameters `fuzz&ea`)
- [ ] Does the sim behave correctly when listener order is shuffled? (run with query
  parameters `ea&listenerOrder=random` and `ea&listenerOrder=random&fuzz`)
- [ ] Does the sim output any deprecation warnings? Run with `?deprecationWarnings`. Do not use deprecated methods in
  new code.

## **Memory Leaks**

Please note that dynamic allocation/linking and disposal are not used in this sim. Models are created once. Views display DynamicProperties across models. The term "dispose" is forbidden via a lint rule.

- [ ] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (This process is
  described [here](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md#47-memory-leak-testing).) Test on a
  version built using `grunt --minify.mangle=false`. Compare to testing results done by the responsible developer.
  Results can be found in https://github.com/phetsims/projectile-data-lab/issues/24
- [ ] For each common-code component (sun, scenery-phet, vegas, …) that opaquely registers observers or listeners, is
  there a call to that component’s `dispose` function, or is it obvious why it isn't necessary, or is there
  documentation about why `dispose` isn't called? An example of why no call to `dispose` is needed is if the component
  is used in a `ScreenView` that would never be removed from the scene graph. Note that it's also acceptable (and
  encouraged!) to describe what needs to be disposed in implementation-notes.md.
- [ ] Are there leaks due to registering observers or listeners? The following guidelines should be followed unless
  documentation (in-line or in implementation-notes.md) describes why following them is not necessary.
  * AXON: `Property.link` or `lazyLink` is accompanied by `unlink`.
  * AXON: `Multilink.multilink` is accompanied by `unmultilink`.
  * AXON: Creation of `Multilink` is accompanied by `dispose`.
  * AXON: Creation of `DerivedProperty` is accompanied by `dispose`.
  * AXON: `Emitter.addListener` is accompanied by `removeListener`.
  * AXON: `ObservableArrayDef.element*Emitter.addListener` is accompanied
    by `ObservableArrayDef.element*Emitter.removeListener`
  * SCENERY: `Node.addInputListener` is accompanied by `removeInputListener`
  * TANDEM: Creation of an instrumented `PhetioObject` is accompanied by `dispose`.
- [ ] All classes that require a `dispose` function should have one. This should expose a public `dispose` function that
  calls `this.dispose{{CLASS_NAME}}()`, where `dispose{{CLASS_NAME}}` is a private function declared in the
  constructor.  `{{CLASS_NAME}}` should exactly match the class name.
- [ ] All classes that do not properly override `dispose` should either (a) use `isDisposable: false`, or (b) implement
  a `dispose` method that calls `Disposable.assertNotDisposable`. Use (a) for classes that inherit a `dispose` method
  from Disposable. Use (b) for classes that inherit a `dispose` method from something other than Disposable. The goal
  here is to prevent clients from calling `dispose` for something that does not properly clean itself up, creating a
  memory leak. This is especially important for common code, but is good defensive programming for sim-specific code.

## **Performance**

- [ ] Play with sim, identify any obvious performance issues. Examples: animation that slows down with large numbers of
  objects; animation that pauses or "hitches" during garbage collection.
- [ ] If the sim uses WebGL, does it have a fallback? Does the fallback perform reasonably well? (run with query
  parameter `webgl=false`). UPDATE: WebGL is not used, but we use canvas for the projectiles and histograms.

## **Usability**

- [ ] Are UI components sufficiently responsive? (especially continuous UI components, such as sliders)
- [ ] Are pointer areas optimized, especially for touch? (run with query parameter `showPointerAreas`). See https://github.com/phetsims/projectile-data-lab/issues/187
- [ ] Do pointer areas overlap? (run with query parameter `showPointerAreas`) Overlap may be OK in some cases, depending on the z-ordering (if the front-most object is supposed to occlude pointer areas) and whether objects can be moved. See https://github.com/phetsims/projectile-data-lab/issues/187

## **Internationalization**

- [ ] Does the sim behave correctly with dynamic layout, to support dynamic locale? Run with `stringTest=dynamic` and
  use the left/right arrow keys.
- [ ] Are there any strings that are not internationalized, and does the sim layout gracefully handle internationalized
  strings that are shorter than the English strings? (run with query parameter `stringTest=X`. You should see nothing
  but 'X' strings.)
- [ ] Does the sim layout gracefully handle internationalized strings that are longer than the English strings? (run
  with query parameters `stringTest=double` and `stringTest=long`)
- [ ] Does the sim stay on the sim page (doesn't redirect to an external page) when running with the query parameter
  `stringTest=xss`? This test passes if sim does not redirect, OK if sim crashes or fails to fully start. Only test on
  one desktop platform. For PhET-iO sims, additionally test `?stringTest=xss` in Studio to make sure i18n strings didn't
  leak to phetioDocumentation, see https://github.com/phetsims/phet-io/issues/1377
- [ ] Avoid using concatenation to create strings that will be visible in the user interface. Use `StringUtils.fillIn`
  and a string pattern to ensure that strings are properly localized. This is relevant in cases where order should be
  translatable.
- [ ] Use named placeholders (e.g. `"{{value}} {{units}}"`) instead of numbered placeholders (e.g. `"{0} {1}"`).
- [ ] #191
  to [string key conventions](https://github.com/phetsims/phet-info/blob/main/doc/string-key-conventions.md). String
  keys are difficult to change after a sim has been published, and they appear in the PhET-iO API (and Studio) as the
  phetioIDs for StringProperties.
- [ ] If the sim was already released, make sure none of the original string keys have changed. If they have changed,
  make sure any changes have a good reason and have been discussed with @jbphet (it is likely that an issue
  like https://github.com/phetsims/gravity-force-lab/issues/166 should be created).

## **Repository Structure**

- [ ] The repository name should correspond to the sim title. For example, if the sim title is "Wave Interference", then
  the repository name should be "wave-interference".
- [ ] Are all required files and directories present? For a sim repository named “my-repo”, the general structure should
  look like this (where assets/, images/, mipmaps/ or sounds/ may be omitted if the sim doesn’t have those types of
  resource files).

  ```
  my-repo/
    assets/
    doc/
      images/
        *see annotation
      model.md
      implementation-notes.md
    images/
      license.json
    js/
      (see section below)
    mipmaps/
      license.json
    sound/
      license.json
    dependencies.json
    .gitignore
    my-repo_en.html
    my-repo-strings_en.json
    Gruntfile.js
    LICENSE
    package.json
    README.md
  ```
  *Any images used in model.md or implementation-notes.md should be added here. Images specific to aiding with
  documentation do not need their own license.

- [ ] Verify that the same image file is not present in both images/ and mipmaps/. If you need a mipmap, use it for all
  occurrences of the image.

- [ ] Is the js/ directory properly structured? All JavaScript source should be in the js/ directory. There should be a
  subdirectory for each screen (this also applies for single-screen sims, where the subdirectory matches the repo name).
  For a multi-screen sim, code shared by 2 or more screens should be in a js/common/ subdirectory. Model and view code
  should be in model/ and view/ subdirectories for each screen and common/. For example, for a sim with screens
  “Introduction” and “Lab”, the general directory structure should look like this:

  ```
  my-repo/
    js/
    common/
      model/
      view/
    introduction/
      model/
      view/
    lab/
      model/
      view/
    my-repo-main.js
    myRepo.js
    myRepoStrings.js
  ```

- [ ] Do filenames use an appropriate prefix? Some filenames may be prefixed with the repository name,
  e.g. `MolarityConstants.js` in molarity. If the repository name is long, the developer may choose to abbreviate the
  repository name, e.g. `EEConstants.js` in expression-exchange. If the abbreviation is already used by another
  repository, then the full name must be used. For example, if the "EE" abbreviation is already used by
  expression-exchange, then it should not be used in equality-explorer. Whichever convention is used, it should be used
  consistently within a repository - don't mix abbreviations and full names. The abbreviation should be all uppercase
  letters; e.g. MOTHAConstants, not MotHAConstants for "Model of the Hydrogen Atom".
- [ ] #194
  1:1 correspondence between asset and resource files; for example, several related images may be in the same .ai file.
  Check license.json for possible documentation of why some resources might not have a corresponding asset file.
- [ ] For simulations, was the README.md generated by `grunt published-README` or `grunt unpublished-README`? Common
  code repos can have custom README files.
- [ ] Is the LICENSE file correct? (Generally GPL v3 for sims and MIT for common code,
  see [this thread](https://github.com/phetsims/tasks/issues/875#issuecomment-312168646) for additional information).
- [ ] Does .gitignore match the one in simula-rasa?
- [ ] In GitHub, verify that all non-release branches have an associated issue that describes their purpose.
- [ ] Are there any GitHub branches that are no longer needed and should be deleted?
- [ ] Sim-specific query parameters (if any) should be identified and documented in one .js file in js/common/ or js/ (
  if there is no common/). The .js file should be named `{{PREFIX}}QueryParameters.js`, for example
  ArithmeticQueryParameters.js for the arithmetic repository, or FBQueryParameters.js for Function Builder (where
  the `FB` prefix is used).
- [ ] Query parameters that are public-facing should be identified using `public: true` in the schema.
- [ ] All sims should use a color file named `MyRepoColors.ts` or, if using abbreviations, `MRColors.ts`, and
  use `ProfileColorProperty` where appropriate, even if they have a single (default) profile (to support color editing
  and PhET-iO Studio). The `ColorProfile` pattern was converted to `*Colors.ts` files in
  https://github.com/phetsims/scenery-phet/issues/515. Please see
  [GasPropertiesColors.ts](https://github.com/phetsims/gas-properties/blob/main/js/common/GasPropertiesColors.ts)
  for a good example.
- [ ] #190
  Properties in `{{PREFIX}}Preferences.ts`, for example KeplersLawsPreferences.ts. The initial value of each such preferences Property should be set via a query parameter from `{{PREFIX}}QueryParameters.js`.
- [ ] Does `package.json` refer to any dependencies that are not used by the sim?
- [ ] Does `package.json` include any config that was only needed for development? For example:
    * Lint rules turned off or made more graceful
    * Certain testing or simFeatures turned off with flags

## **Coding Conventions**

- [ ] Are coding conventions outlined in
  PhET's [Coding Conventions](https://github.com/phetsims/phet-info/blob/main/doc/coding-conventions.md) document
  followed and adhered to? This document deals with PhET coding conventions. You do not need to exhaustively check every
  item in this section, nor do you necessarily need to check these items one at a time. The goal is to determine whether
  the code generally meets PhET standards.

## **TypeScript Conventions**

- [ ] Are TypeScript conventions outlined in
  PhET's [TypeScript Conventions](https://github.com/phetsims/phet-info/blob/main/doc/typescript-conventions.md)
  document followed and adhered to?

## **Math Libraries**

- [ ] `DOT/Utils.toFixed` or `DOT/Utils.toFixedNumber` should be used instead of `toFixed`. JavaScript's `toFixed` is
  notoriously buggy. Behavior differs depending on browser, because the spec doesn't specify whether to round or floor.

## IE11

- [ ] IE is no longer supported. With that in mind remove IE-specific workarounds
- [ ] Use `string.includes` and `string.startsWith` where possible.

## **Organization, Readability, and Maintainability**

- [ ] Does the organization and structure of the code make sense? Do the model and view contain types that you would
  expect (or guess!) by looking at the sim? Do the names of things correspond to the names that you see in the user
  interface?
- [ ] Are appropriate design patterns used?
  See [phet-software-design-patterns.md](https://github.com/phetsims/phet-info/blob/main/doc/phet-software-design-patterns.md).
  If new or inappropriate patterns are identified, create an issue.
- [ ] Is inheritance used where appropriate? Does the type hierarchy make sense?
- [ ] Is composition favored over inheritance where appropriate?
  See https://en.wikipedia.org/wiki/Composition_over_inheritance.
- [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary
  properties/functions). If you only need a few fields from a large object, pass them in as separate parameters. The
  threshold for the number of parameters is up to you - use your judgement. Alternatively in TypeScript, you can
  decouple by narrowing the API using `Pick`, but this is a bit of a hack. Here's an example:

```ts
  public constructor( tickMarksVisibleProperty: Property<boolean>,
                      model: Pick<IntroModel, 'changeWaterLevel'>, // <-- Note the call site can pass the whole model, but we declare we will only use this part of it
                      waterCup: WaterCup, modelViewTransform: ModelViewTransform2,
                      providedOptions?: WaterCup3DNodeOptions ) {
```

- [ ] Is there too much unnecessary decoupling? (e.g. by passing all of the properties of an object independently
  instead of passing the object itself)?  UPDATE: See for instance HistogramNode.ts
- [ ] Are the source files reasonable in size? Scrutinize large files with too many responsibilities - can
  responsibilities be broken into smaller delegates? To see file sizes for TypeScript sims, run this shell command:

```
cd {{repo}}/js ; wc -l `find . -name "*.ts" -print` | sort
```

<details>

```
~/phet/root/projectile-data-lab/js$ wc -l `find . -name "*.ts" -print` | sort
       9 ./common/model/MysteryOrCustom.ts
       9 ./common/model/ScreenIdentifier.ts
       9 ./common/model/SingleOrContinuous.ts
      10 ./common/BinStrategy.ts
      10 ./common/model/HistogramRepresentation.ts
      10 ./projectileDataLab.ts
      12 ./common-vsm/model/VSMFieldIdentifier.ts
      13 ./common/model/HistogramData.ts
      15 ./sampling/model/SamplingPhase.ts
      19 ./common/model/LauncherConfiguration.ts
      20 ./measures/view/MeasuresKeyboardHelpNode.ts
      20 ./sampling/view/SamplingKeyboardHelpNode.ts
      20 ./sources/view/SourcesKeyboardHelpNode.ts
      20 ./variability/view/VariabilityKeyboardHelpNode.ts
      25 ./common/view/PDLText.ts
      27 ./common/view/PDLKeyboardHelpNode.ts
      27 ./sampling/view/SamplingKeyboardShortcutsHelpSection.ts
      28 ./common/view/PDLCheckboxRow.ts
      28 ./common/view/SectionMysteryLauncher.ts
      30 ./common-vsm/view/VSMKeyboardShortcutsHelpSection.ts
      30 ./common/view/MysteryLauncherIcon.ts
      31 ./common/view/MeanIndicatorNode.ts
      34 ./common/view/PDLPanel.ts
      37 ./variability/view/VariabilityLaunchPanel.ts
      38 ./common/PDLUtils.ts
      38 ./sources/view/SourcesLaunchPanel.ts
      39 ./common-sm/model/SMField.ts
      39 ./measures/MeasuresScreen.ts
      39 ./sampling/SamplingScreen.ts
      39 ./sources/SourcesScreen.ts
      39 ./variability/VariabilityScreen.ts
      40 ./common-sm/model/SMModel.ts
      40 ./common-vsm/view/VSMLaunchPanel.ts
      41 ./common/view/PDLRectangularRadioButtonGroup.ts
      43 ./measures/view/MeasuresLaunchPanel.ts
      43 ./variability/model/VariabilityModel.ts
      44 ./common/view/PDLLaunchPanel.ts
      45 ./sampling/view/SamplingLaunchPanel.ts
      47 ./common-vsm/view/LauncherFlashNode.ts
      47 ./common/model/MeanTone.ts
      49 ./common/view/HistogramRepresentationIconNode.ts
      49 ./common/view/PDLPanelSection.ts
      50 ./common-sm/view/SectionCustomLauncher.ts
      50 ./common/model/ProjectileType.ts
      51 ./common-vsm/view/VSMHistogramNode.ts
      52 ./common/view/HistogramAccordionBox.ts
      52 ./sampling/view/SectionSampleSize.ts
      54 ./common-vsm/view/VSMFieldSignNode.ts
      54 ./common/model/ProjectileSound.ts
      55 ./projectile-data-lab-main.ts
      57 ./sources/model/SourcesModel.ts
      61 ./common-vsm/model/LauncherMechanism.ts
      65 ./sampling/view/SamplingFieldSignNode.ts
      69 ./measures/view/MeasuresInteractiveToolPanel.ts
      74 ./common-vsm/view/PDLStopwatchNode.ts
      75 ./variability/view/VariabilityScreenView.ts
      76 ./measures/view/MeasuresStaticToolPanel.ts
      77 ./common/view/SectionLauncherConfiguration.ts
      79 ./common-sm/view/CustomLauncherTypeRadioButtonGroup.ts
      84 ./common/model/PDLEventTimer.ts
      84 ./common/view/SectionProjectileType.ts
      86 ./sampling/view/SamplingCanvasNode.ts
      87 ./common/PDLQueryParameters.ts
      88 ./sources/view/SourcesScreenView.ts
      92 ./ProjectileDataLabStrings.ts
      92 ./common/view/LauncherIconNode.ts
      95 ./common-vsm/view/FieldRadioButtonGroup.ts
      96 ./common/view/LaunchButton.ts
      97 ./common/view/FieldOverlayNode.ts
      98 ./common/view/SimulationPreferencesContentNode.ts
     104 ./common-vsm/view/VSMCanvasNode.ts
     105 ./common/PDLConstants.ts
     105 ./sampling/view/SamplingHistogramNode.ts
     110 ./sampling/view/SamplingAccordionBox.ts
     111 ./common-vsm/view/TimeDisplayNode.ts
     111 ./measures/view/SectionAnyLauncher.ts
     112 ./common-vsm/view/InteractiveToolPanel.ts
     117 ./common/view/FieldSignNode.ts
     119 ./common/model/Launcher.ts
     119 ./common/view/BinControlNode.ts
     120 ./measures/view/MeasuresScreenView.ts
     132 ./common-vsm/view/AngleStabilizerSection.ts
     132 ./common/view/MysteryLauncherRadioButtonGroupWrapper.ts
     135 ./common/model/Histogram.ts
     136 ./common/view/HistogramCanvasPainter.ts
     138 ./measures/model/MeasuresField.ts
     143 ./common-vsm/view/StaticToolPanel.ts
     143 ./measures/model/IntervalTool.ts
     150 ./common-vsm/view/SpeedToolNode.ts
     151 ./common/view/SelectorNode.ts
     156 ./sampling/view/SampleSelectorNode.ts
     157 ./common/view/PDLCanvasNode.ts
     159 ./common-vsm/view/AngleToolNode.ts
     162 ./common/model/HistogramSonifier.ts
     163 ./common/view/FieldNode.ts
     163 ./measures/view/MeasuresHistogramNode.ts
     167 ./common/view/PDLScreenIconFactory.ts
     190 ./measures/model/MeasuresModel.ts
     195 ./common/model/PDLModel.ts
     202 ./common-vsm/view/ProjectileSelectorNode.ts
     204 ./common-vsm/view/CustomLauncherNode.ts
     212 ./sampling/view/SampleSizeThumbnailNode.ts
     213 ./common/model/Projectile.ts
     222 ./common/PDLColors.ts
     234 ./common-vsm/model/VSMField.ts
     242 ./measures/view/DataMeasuresOverlay.ts
     245 ./sampling/view/SamplingScreenView.ts
     264 ./common/view/PDLScreenView.ts
     273 ./sampling/model/SamplingModel.ts
     284 ./common-vsm/model/VSMModel.ts
     318 ./common-vsm/view/HeatMapToolNode.ts
     338 ./common-vsm/view/VSMScreenView.ts
     348 ./common/model/Field.ts
     363 ./common/view/LauncherNode.ts
     383 ./common/view/HistogramNode.ts
     388 ./sampling/model/SamplingField.ts
     418 ./measures/view/IntervalToolNode.ts
   12458 total

```

</details>

- [ ] Are any significant chunks of code duplicated? In addition to manual identification, tools include: WebStorm
  _Code > Analyze Code > Locate Duplicates_ and https://github.com/danielstjules/jsinspect.   UPDATE: There are a few "cost 26" things at the worst. This amounts to about 2-3 lines of code, and does not seem worrisome.
- [ ] Is there anything that should be generalized and migrated to common code?
- [ ] Are there any `TODO` or `FIXME` or `REVIEW` comments in the code? They should be addressed or promoted to GitHub
  issues.
  - This means that there should be no TODOs pointing to https://github.com/phetsims/tasks/issues/1129
  - This means that your repo should have the `"todo-should-have-repo"` lint rule enabled.
- [ ] Are there any [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) that should be factored
  out as constants and documented?
- [ ] Are there any constants that are duplicated in multiple files that should be factored out into
  a `{{REPO}}Constants.js` file?
- [ ] Does the implementation rely on any specific constant values that are likely to change in the future? Identify
  constants that might be changed in the future. (Use your judgement about which constants are likely candidates.) Does
  changing the values of these constants break the sim? For example,
  see https://github.com/phetsims/plinko-probability/issues/84.
- [ ] Is [PhetColorScheme](https://github.com/phetsims/scenery-phet/blob/main/js/PhetColorScheme.ts) used where
  appropriate? Verify that the sim is not inventing/creating its own colors for things that have been standardized
  in `PhetColorScheme`. Identify any colors that might be worth adding to `PhetColorScheme`.
- [ ] Are all dependent Properties modeled as `DerivedProperty` instead of `Property`?
- [ ] All dynamics should be called from Sim.step(dt), do not use window.setTimeout or window.setInterval. This will
  help support Legends of Learning and PhET-iO.

## **Accessibility**

This section may be omitted if the sim has not been instrumented with accessibility features. Accessibility includes
various features, not all are always include. Ignore sections that do not apply.

### General

- [ ] Are accessibility features integrated well into the code? They should be added in a maintainable way, even if that
  requires upfront refactoring.

### Alternative Input

- [ ] Does the sim pass an accessibility fuzz test? (run with query parameters `fuzzBoard&ea`)
- [ ] Does the sim use `ScreenView.pdomPlayAreaNode.pdomOrder` and `Screenview.pdomControlAreaNode.pdomOrder` to control
  the traversal order and categorize Nodes in the PDOM? See alternative-input-quickstart-guide.md for more information. This is being completed in https://github.com/phetsims/projectile-data-lab/issues/107
- [ ] Does this sim use specific keyboard shortcuts that overlap with global shortcuts? This includes the use of
  modifier keys like in https://github.com/phetsims/ratio-and-proportion/issues/287. **NOTE: There is currently no list
  of global shortcuts, and therefore no way to complete this checklist item.
  See https://github.com/phetsims/phet-info/issues/188.**
**NOTE 2: This was addressed in #61 and #63**

## **PhET-iO**

This section may be omitted if the sim has not been instrumented for PhET-iO, but is likely good to glance at no matter.

- [ ] Does instrumentation follow the conventions described
  in [PhET-iO Instrumentation Guide](https://github.com/phetsims/phet-io/blob/main/doc/phet-io-instrumentation-technical-guide.md)?
  This could be an extensive bullet. At the very least, be sure to know what amount of instrumentation this sim
  supports. Describing this further goes beyond the scope of this document.
- [ ] PhET-iO instantiates different objects and wires up listeners that are not present in the PhET-branded simulation.
  It needs to be tested separately for memory leaks. To help isolate the nature of the memory leak, this test should be
  run separately from the PhET brand memory leak test. Test with a colorized Data Stream, and Studio (easily accessed
  from phetmarks). Compare to testing results done by the responsible developer and previous releases.
- [ ] Make sure unused `PhetioObject` instances are disposed, which unregisters their tandems.
- [ ] Make sure JOIST `dt` values are used instead of `Date.now()` or other Date functions. Perhaps try
  `phet.joist.elapsedTime`. Though this has already been mentioned, it is necessary for reproducible playback via input
  events and deserves a comment in this PhET-iO section.
- [ ] Are random numbers using `DOT/dotRandom` as an imported module (not a global), and all doing so after modules are
  declared (non-statically)? For example, the following methods (and perhaps others) should not be
  used: `Math.random`, `_.shuffle`, `_.sample`, `_.random`. This also deserves re-iteration due to its effect on
  record/playback for PhET-iO.
- [ ] Like JSON, keys for `undefined` values are omitted when serializing objects across frames. Consider this when
  determining whether `toStateObject` should use `null` or `undefined` values.
- [ ] PhET prefers to use the term "position" to refer to the physical (x,y) position of objects. This applies to both
  brands, but is more important for the PhET-iO API. See https://github.com/phetsims/phet-info/issues/126
- [ ] Are your IOType state methods violating the API of the core type by accessing private fields?
- [ ] When defining a boolean Property to indicate whether something is enabled with a tandem name of `enabledProperty`,
  use `AXON/EnabledProperty`. This should be done in both the model and the view. If you're using a DerivedProperty,
  skip this item.
- [ ] Do not use translated strings in `phetioDocumentaton` - it changes the PhET-iO API!

**Comment by pixelzoom** [comment]
Code review is done, issues linked above.  This sim is in great shape - well done! 

While I took the sim for a spin in Studio, it was a quick spin, and I assumed that the tree structure has already been vetted.  The tree structure seems logical and well-organized.  I noticed and fixed only one PhET-iO problem: https://github.com/phetsims/projectile-data-lab/commit/391b4efbd69d26731d91ebe375ccfc856369e011.

Back to @matthew-blackman and @samreid to wrap up.  Let me know if you have questions. Close this issue when you're done.

**Comment by matthew-blackman** [comment]
All remaining work is being tracked in separate issues. Nice work all! Closing.
